name: deep-storm3d
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - expat=2.5.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.12.2
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - contourpy==1.2.0
    - cycler==0.12.1
    - filelock==3.9.0
    - fonttools==4.50.0
    - fsspec==2023.4.0
    - imageio==2.34.0
    - jinja2==3.1.2
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - markupsafe==2.1.3
    - matplotlib==3.8.3
    - mpmath==1.3.0
    - networkx==3.2.1
    - numpy==1.26.4
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cudnn-cu11==8.7.0.84
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-nccl-cu11==2.19.3
    - nvidia-nvtx-cu11==11.8.86
    - packaging==24.0
    - pillow==10.2.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - scikit-image==0.22.0
    - scikit-learn==1.4.1.post1
    - scipy==1.12.0
    - six==1.16.0
    - sympy==1.12
    - threadpoolctl==3.4.0
    - tifffile==2024.2.12
    - torch==2.2.1+cu118
    - torchvision==0.17.1+cu118
    - typing-extensions==4.8.0