name: deep-storm3d
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - libexpat=2.6.2
  - libffi=3.4.4
  - libsqlite=3.45.2
  - libzlib=1.2.13
  - openssl=3.2.1
  - pip=24.0
  - python=3.12.2
  - setuptools=69.2.0
  - tk=8.6.13
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wheel=0.42.0
  - xz=5.4.6
  - pip:
    - contourpy==1.2.0
    - cycler==0.12.1
    - filelock==3.9.0
    - fonttools==4.50.0
    - fsspec==2023.4.0
    - imageio==2.34.0
    - jinja2==3.1.2
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - markupsafe==2.1.3
    - matplotlib==3.8.3
    - mpmath==1.3.0
    - networkx==3.2.1
    - numpy==1.26.4
    - packaging==24.0
    - pillow==10.2.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - scikit-image==0.22.0
    - scikit-learn==1.4.1.post1
    - scipy==1.12.0
    - six==1.16.0
    - sympy==1.12
    - threadpoolctl==3.3.0
    - tifffile==2024.2.12
    - torch==2.2.1+cu118
    - torchvision==0.17.1+cu118
    - typing-extensions==4.8.0
